# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ca5e3f7f82e1ce50867c8ee0858f7a72"
name = "hello-world"
handle = "hello-world-488"
application_url = "https://mating-conference-leader-scored.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mating-conference-leader-scored.trycloudflare.com/auth/callback",
  "https://mating-conference-leader-scored.trycloudflare.com/auth/shopify/callback",
  "https://mating-conference-leader-scored.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
